In [2]:
from src.rotation import *
from src.hybrid_operations import *
from src.hybrid_math import *
from src.file_utils import *
from src.camera import PinholeCamera, Camera
from src.geometry import *
from src.pose import interpolate_pose, Pose
import numpy as np

from numpy.testing import assert_almost_equal
from src.camera import PinholeCamera

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [3]:
test_cam = PinholeCamera.from_K(
    K = [[5.07080109e+002, 0., 3.11488770e+002],
         [0.,5.07080109e+002,  2.10904282e+002],
         [0., 0., 1.]],
    image_size = [640,480],
    dist=[1.30847082e-001,-3.39481622e-001, -1.97465792e-002, -3.00327875e-003, 0.]
)

print(test_cam._is_distorted())

True


In [22]:
print(test_cam.radial_params)
print(test_cam.tangential_params)

(0.130847082, -0.339481622, 0.0)
(-0.0197465792, -0.00300327875)


In [5]:
from numpy.testing import assert_almost_equal

expected_uv = test_cam.make_pixel_grid()[:,292470:292471]
print(expected_uv)
rays = test_cam.get_rays(uv=expected_uv,max_iter=5)
print(rays)
projected_uv = test_cam.project_rays(rays)
print(np.abs(projected_uv - expected_uv).max())
print(projected_uv)
# assert_almost_equal(np.array([1.,2.,3.]) ,np.array([1.,2.,2.]),decimal=8)
# assert_almost_equal(expected_uv,projected_uv,decimal=1)

[[630]
 [456]]
[[-0.76497878]
 [-0.64403204]
 [ 0.00549416]]
26303025399596.094
[[2.63030254e+13]
 [2.21443934e+13]]
